#!/usr/bin/env python

#append the path with the folder above this one
#means we can run tests from here and import files ok
#probablly a better way to do this. I'll figure it out later
import sys
sys.path.append("../")

import unittest
from Master.JobManager import JobManager

def get_job_info(id_num=1, tasks=10, width=500, height=500):
    data = {}
    data['job_id']     = id_num
    data['job_name']   = 'Test Job'
    data['tasks']      = tasks

    data['job_data']   = {}
    data['job_data']['job_type']    = 'PovJob'
    data['job_data']['pov_file']    = 'misc/fractal2.pov'
    data['job_data']['output_file'] = 'output-%s' % id_num
    data['job_data']['width']       = width
    data['job_data']['height']      = height
    data['job_data']['extras']      = ['+FN']
    return data


class JobManagerBehavior(unittest.TestCase):

    def testAddJobs(self):
        jobmanager = JobManager()
        jobmanager.new_job(get_job_info(1))
        jobmanager.new_job(get_job_info(2))
        self.assertEqual(len(jobmanager.new_jobs), 2)

    def testActivateJob(self):
        jobmanager = JobManager()
        jobmanager.new_job(get_job_info(1))
        jobmanager.new_job(get_job_info(2))
        self.assertEqual(len(jobmanager.new_jobs), 2)
        new_tasks = jobmanager.activate_tasks()
        self.assertEqual(len(jobmanager.new_jobs), 0)
        self.assertEqual(len(jobmanager.running_jobs), 2)

    def testFinishedTask(self):
        jobmanager = JobManager()
        jobmanager.new_job(get_job_info(1))
        new_tasks = jobmanager.activate_jobs()
        jobmanager.finished_task(new_tasks.pop())
        #not totally sure what to test for here yet

    def testFinishedJobs(self):
        jobmanager = JobManager()
        jobmanager.new_job(get_job_info(1))
        new_tasks = jobmanager.activate_jobs()
        for task in new_tasks:
            job_manager.finished_task(task)
        jobs = jobmanager.get_finished_jobs()
        fin_job_id = jobs.pop().data['job_id']
        self.assertEqual(in_job_id, 1)
        self.assertEqual(len(jobmanager.new_jobs), 0)
        self.assertEqual(len(jobmanager.running_jobs), 0)

if __name__ == '__main__':
    unittest.main()


