#!/usr/bin/env python

from Master.PovJob import PovJob
import random


def get_job():
    data = {}
    data['pov_file']    = 'misc/fractal2.pov'
    data['job_id']      = str(random.randint(0,1000))
    data['output_file'] = str(random.randint(0,1000)) + 'output.png'
    data['width']       = 500
    data['height']      = str(400 + random.randint(0, 400))
    data['tasks']       = random.randint(3, 10)
    data['extras']      = ["+FN"]
    return data

def main():
    new_job = get_job()
    print "%s:  %s,%s,%s" % (new_job['job_id'], new_job['width'], new_job['height'], new_job['tasks'])
    pov_job = PovJob(new_job['job_id'], new_job)
    pov_job.create_tasks()

    while not pov_job.all_finished():
        task = pov_job.get_task()
        print task
        pov_job.finished_task(task)
    print pov_job.get_output()

if __name__ == '__main__':
    main()


